name: Cool react Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cybersapient
  CLUSTER_NAME: cool-k8s-cluster
  CLUSTER_ZONE: europe-west1-b
  REPO_NAME: react-app
  IMAGE: europe-west1-docker.pkg.dev/cybersapient/react-app/frontend-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker to push to Artifact Registry
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE:${{ github.sha }} .
        docker push $IMAGE:${{ github.sha }}

    - name: Set up gcloud CLI and kubectl
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: kubectl

    - name: Get GKE Credentials
      run: gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE

    - name: Set up Helm
      uses: azure/setup-helm@v4

    - name: Deploy via Helm
      run: |
        helm upgrade --install frontend ./helm/frontend \
          --set image.repository=$IMAGE \
          --set image.tag=${{ github.sha }}
